# Generated by Django 5.2.7 on 2026-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='news/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Pre-school', 'Pre-school (6 weeks - 2 years)'), ('NURSERY', 'Nursery (3-5 years)'), ('PRIMARY', 'Primary (6-11 years)'), ('JSS', 'Junior Secondary (12-14 years)'), ('SSS', 'Senior Secondary (15-18 years)')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age_range', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('curriculum', models.TextField(help_text='Nigerian curriculum details')),
                ('islamic_studies', models.TextField(help_text='Quran, Arabic, Islamic studies')),
                ('admission_requirements', models.TextField()),
                ('fees_summary', models.TextField(help_text='Brief fee summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_levels/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('staff_type', models.CharField(choices=[('PROPRIETRESS', 'Proprietress'), ('PRINCIPAL', 'Principal'), ('HEAD_TEACHER', 'Head Teacher'), ('TEACHER', 'Teacher'), ('QURAN_TEACHER', "Qur'an Teacher"), ('ADMIN', 'Administrator')], max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('qualifications', models.TextField()),
                ('quran_certification', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='staff/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['staff_type', 'order'],
            },
        ),
    ]
