# Generated by Django 5.2.7 on 2026-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_excellence', models.IntegerField(default=25, help_text='Number of years the school has been operating')),
                ('total_students', models.IntegerField(default=500, help_text='Total number of students enrolled')),
                ('total_graduates', models.IntegerField(default=1000, help_text='Total number of graduates')),
            ],
            options={
                'verbose_name_plural': 'School Information',
            },
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='level',
            field=models.CharField(choices=[('Pre-school', 'Pre-school (2 years-3 years)'), ('NURSERY', 'Nursery (3-5 years)'), ('PRIMARY', 'Primary (6-11 years)'), ('JSS', 'Junior Secondary (12-14 years)'), ('SSS', 'Senior Secondary (15-18 years)')], max_length=20, unique=True),
        ),
    ]
