# Generated by Django 5.2.7 on 2026-05-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('session', models.CharField(choices=[('2025/2026', '2025/2026 Session'), ('2026/2027', '2026/2027 Session')], default='2025/2026', max_length=20)),
                ('quran_memorization', models.CharField(blank=True, help_text='Portion memorized (e.g., 5 Juz, Completed Quran)', max_length=200)),
                ('can_recite_quran', models.BooleanField(default=False, help_text='Can recite Quran with Tajweed?')),
                ('islamic_knowledge', models.TextField(blank=True, help_text='Basic Islamic knowledge summary')),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian')], max_length=50)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLIST', 'Waitlist')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('applying_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoollevel')),
            ],
            options={
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
