# Generated by Django 5.2.7 on 2026-06-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, help_text='Short name or nickname', max_length=100)),
                ('photo', models.ImageField(upload_to='graduands/')),
                ('aspiration', models.TextField(help_text='Future aspiration or career goal')),
                ('favorite_memory', models.TextField(help_text='Favorite memory from school')),
                ('message', models.TextField(help_text='Message to school or younger students')),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements')),
                ('future_plans', models.CharField(blank=True, help_text='Plans after graduation', max_length=200)),
                ('graduation_year', models.CharField(default='2025', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Graduands',
                'ordering': ['order', 'name'],
            },
        ),
    ]
