# Generated by Django 5.2.7 on 2026-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('PROPRIETOR', 'Proprietor'), ('DIRECTOR OF STUDIES', 'Director of studies'), ('PRINCIPAL', 'Principal'), ('HEAD_TEACHER', 'Head Teacher'), ('TEACHER', 'Teacher'), ('QURAN_TEACHER', "Qur'an Teacher"), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
