# Generated by Django 5.2.7 on 2026-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staff_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
