# Generated by Django 5.2.7 on 2026-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gallery_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
