# Generated by Django 5.2.7 on 2026-08-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
