# Generated by Django 5.2.7 on 2026-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_image_alter_gallery_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollevel',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
