# Generated by Django 5.2.7 on 2026-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_schoollevel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='birth_certificate',
            field=models.FileField(default='default', upload_to='admissions/birth_certificates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='immunization_records',
            field=models.FileField(blank=True, null=True, upload_to='admissions/immunization_records/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='admissions/passport_photos/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='previous_school_report',
            field=models.FileField(blank=True, null=True, upload_to='admissions/school_reports/'),
        ),
    ]
